Hw08 envdir tool
Al-Sher/hw_otus pull request #8
Opened 2023-05-17 06:02 UTC by Al-Sher

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-05-17 16:53 UTC, dshemin requested changes

2023-05-17 16:53 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		content, err := os.ReadFile(dir + "/" + entity.Name())
Критично:

>  имя `S` не должно содержать `=`

Отсутствует данная проверка.

2023-05-17 16:53 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		needRemove := false
Важно:

Можно упростить код до: `needRemove := str == ""`

2023-05-17 16:53 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	c.Stdout = os.Stdout
Критично:

> стандартные потоки ввода/вывода/ошибок пробрасывались в вызываемую программу;

Потерялся stdin

2023-05-17 17:33 UTC, Al-Sher commented on hw08_envdir_tool/env_reader.go
> +		content, err := os.ReadFile(dir + "/" + entity.Name())
Поправил

2023-05-18 09:20 UTC, dshemin approved these changes

2023-05-19 04:09 UTC, merged